# TORVAN MEDICAL DEVICE - PRODUCTION ENVIRONMENT CONFIGURATION
# ============================================================
# 
# GitHub Environment configuration for production deployment
# Medical device production environment with strict controls and compliance

name: production
description: "TORVAN Medical Device Production Environment - FDA Validated"

# Environment protection rules - STRICT for medical device production
protection_rules:
  required_reviewers: 2        # Require 2 approvals for production
  wait_timer: 300             # 5 minute wait time for manual verification
  prevent_self_review: true   # Author cannot approve their own deployment
  restrict_pushes_to_main: true

# Reviewers who can approve production deployments
deployment_protection_rules:
  - type: "required_reviewers"
    reviewers:
      - type: "team"
        name: "medical-device-leads"
      - type: "team" 
        name: "quality-assurance"
    review_timeout: 3600  # 1 hour timeout for reviews

# Environment variables for production
variables:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.torvan.dev"
  NEXT_PUBLIC_APP_URL: "https://torvan.dev"
  NEXT_PUBLIC_ENVIRONMENT: "production"
  
  # Database configuration
  DB_HOST: "prod-db-primary.torvan.dev"
  DB_PORT: "5432"
  DB_NAME: "torvan_production"
  DB_SSL: "require"
  DB_SSL_MODE: "verify-full"
  
  # Application configuration
  APP_NAME: "TORVAN Medical Device Management"
  APP_VERSION: "production"
  LOG_LEVEL: "info"  # Reduced logging for production performance
  
  # Feature flags for production
  ENABLE_DEBUG_FEATURES: "false"
  ENABLE_TEST_DATA: "false"
  ENABLE_PERFORMANCE_MONITORING: "true"
  ENABLE_SECURITY_MONITORING: "true"
  
  # Medical device specific - PRODUCTION SETTINGS
  MEDICAL_DEVICE_MODE: "production"
  FDA_VALIDATION_MODE: "production"
  AUDIT_LEVEL: "comprehensive"
  COMPLIANCE_REPORTING: "enabled"
  
  # Security settings
  SESSION_TIMEOUT: "1800"      # 30 minutes
  MAX_LOGIN_ATTEMPTS: "3"
  ACCOUNT_LOCKOUT_DURATION: "900"  # 15 minutes
  
  # Performance and scaling
  EXTERNAL_API_TIMEOUT: "10000"
  RATE_LIMIT_REQUESTS: "500"   # More restrictive for production
  RATE_LIMIT_WINDOW: "3600"
  
  # High availability settings
  DB_CONNECTION_POOL_SIZE: "20"
  CACHE_TTL: "300"
  CDN_ENABLED: "true"

# Critical secrets for production - MUST be configured in GitHub Secrets
required_secrets:
  # Database connection (encrypted)
  - PROD_DATABASE_URL
  - DB_USER_PRODUCTION
  - DB_PASSWORD_PRODUCTION
  - DB_READONLY_USER
  - DB_READONLY_PASSWORD
  
  # Authentication (rotating secrets)
  - NEXTAUTH_SECRET_PRODUCTION
  - NEXTAUTH_URL_PRODUCTION
  - JWT_SIGNING_KEY
  - OAUTH_CLIENT_SECRET
  
  # External services
  - SMTP_HOST_PRODUCTION
  - SMTP_USER_PRODUCTION  
  - SMTP_PASSWORD_PRODUCTION
  
  # Monitoring and observability
  - DATADOG_API_KEY_PRODUCTION
  - SENTRY_DSN_PRODUCTION
  - NEW_RELIC_LICENSE_KEY
  - PROMETHEUS_TOKEN
  
  # Medical device compliance and audit
  - FDA_API_KEY_PRODUCTION
  - AUDIT_ENCRYPTION_KEY_PRODUCTION
  - COMPLIANCE_REPORTING_KEY
  - RISK_MANAGEMENT_API_KEY
  
  # Payment processing (PCI compliance)
  - STRIPE_SECRET_KEY_PRODUCTION
  - STRIPE_WEBHOOK_SECRET
  
  # Cloud infrastructure
  - AWS_ACCESS_KEY_ID_PRODUCTION
  - AWS_SECRET_ACCESS_KEY_PRODUCTION
  - AWS_REGION
  
  # Backup and disaster recovery
  - BACKUP_ENCRYPTION_KEY
  - DR_SITE_ACCESS_KEY
  
  # SSL certificates
  - SSL_CERTIFICATE
  - SSL_PRIVATE_KEY

# Production deployment configuration
deployment:
  provider: "kubernetes"
  cluster: "torvan-production"
  namespace: "torvan-prod"
  
  # High availability configuration
  replicas: 5  # Minimum 5 replicas for medical device HA
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  
  # Anti-affinity rules for resilience
  pod_anti_affinity:
    required: true
    topology_key: "kubernetes.io/hostname"
  
  # Health check configuration (strict)
  health_check:
    path: "/api/health"
    port: 3000
    initial_delay: 60
    period: 5
    timeout: 3
    failure_threshold: 2
    success_threshold: 2
  
  # Readiness probe
  readiness_check:
    path: "/api/ready"
    port: 3000
    initial_delay: 30
    period: 5
    timeout: 3
    failure_threshold: 3
  
  # Auto-scaling (conservative for medical device)
  autoscaling:
    enabled: true
    min_replicas: 5
    max_replicas: 20
    target_cpu_utilization: 60  # Conservative scaling
    scale_up_cooldown: "300s"
    scale_down_cooldown: "600s"
  
  # Rolling update strategy
  rolling_update:
    max_unavailable: "25%"
    max_surge: "25%"
  
  # Service mesh configuration
  service_mesh:
    enabled: true
    mutual_tls: true
    traffic_policy: "strict"

# Comprehensive monitoring for medical device production
monitoring:
  enabled: true
  
  # Application metrics
  metrics:
    - response_time_p50
    - response_time_p95
    - response_time_p99
    - error_rate
    - throughput
    - active_users
    - database_connections
    - database_query_time
    - memory_usage
    - cpu_usage
    - disk_usage
    - network_io
  
  # Medical device specific metrics
  medical_metrics:
    - bom_generation_time
    - order_processing_time
    - quality_control_checks
    - audit_log_entries
    - security_events
    - compliance_violations
  
  # Critical alerts for production
  critical_alerts:
    - name: "Service Down"
      condition: "availability < 99.9%"
      severity: "critical"
      notify: ["oncall", "medical-device-team"]
    
    - name: "High Error Rate"
      condition: "error_rate > 1%"
      severity: "critical"
      notify: ["oncall", "development-team"]
    
    - name: "Database Issues"
      condition: "db_connections > 90% OR db_query_time > 1s"
      severity: "critical"
      notify: ["oncall", "database-team"]
    
    - name: "Security Event"
      condition: "security_events > 0"
      severity: "critical"
      notify: ["security-team", "compliance-team"]
  
  # Warning alerts
  warning_alerts:
    - name: "High Response Time"
      condition: "response_time_p95 > 2s"
      severity: "warning"
    
    - name: "Memory Usage High"
      condition: "memory_usage > 80%"
      severity: "warning"
    
    - name: "BOM Generation Slow"
      condition: "bom_generation_time > 4s"
      severity: "warning"
      description: "Medical device requirement: BOM generation < 5s"

# Production security configuration
security:
  # Network security policies
  network_policies:
    - name: "deny-all-default"
      policy_type: "Ingress"
      action: "deny"
    
    - name: "allow-https-ingress"
      policy_type: "Ingress"
      from: ["load-balancer"]
      ports: [443]
    
    - name: "allow-database-egress"
      policy_type: "Egress"
      to: ["database-subnet"]
      ports: [5432]
  
  # Pod security standards
  pod_security:
    standard: "restricted"
    run_as_non_root: true
    run_as_user: 65534  # nobody user
    read_only_root_filesystem: true
    security_context:
      capabilities:
        drop: ["ALL"]
      seccomp_profile:
        type: "RuntimeDefault"
  
  # Secrets management
  secrets_management:
    provider: "kubernetes-secrets"
    encryption_at_rest: true
    rotation:
      enabled: true
      schedule: "monthly"
      notify_before_expiry: "14d"
  
  # TLS configuration
  tls:
    min_version: "1.3"
    cipher_suites: ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256"]
    certificate_transparency: true

# Medical device compliance configuration
medical_device:
  # Regulatory compliance
  compliance:
    fda_cfr_21_part_820: true
    iso_13485: true
    iec_62304: true
    hipaa: true
    sox_compliance: true
  
  # Quality management system
  qms:
    change_control: "mandatory"
    risk_management: "iso14971"
    design_controls: "fda_820_30"
    corrective_preventive_actions: "enabled"
  
  # Audit and traceability
  audit:
    log_all_user_actions: true
    log_all_system_changes: true
    log_all_data_access: true
    encrypt_audit_logs: true
    digital_signatures: true
    retention_period: "25y"  # FDA requirement for device history records
    immutable_storage: true
  
  # Risk management
  risk_management:
    continuous_monitoring: true
    automated_risk_assessment: true
    incident_reporting: "immediate"
    risk_register_updates: "real-time"
  
  # Change control process
  change_control:
    required_approvals: 3  # Medical Device Lead, QA, Regulatory
    documentation_required: true
    risk_assessment_required: true
    testing_required: true
    rollback_plan_required: true
    validation_required: true
  
  # Clinical data protection
  clinical_data:
    encryption_at_rest: "AES-256"
    encryption_in_transit: "TLS 1.3"
    data_anonymization: true
    access_logging: "comprehensive"
    data_retention: "per_regulatory_requirements"

# Disaster recovery and business continuity
disaster_recovery:
  # Backup configuration
  backup:
    enabled: true
    frequency: "hourly"
    retention: "7y"  # Medical device record retention
    encryption: "AES-256"
    geographic_replication: true
    
    # Backup verification
    verification:
      enabled: true
      schedule: "daily"
      restore_testing: "monthly"
  
  # Point-in-time recovery
  pitr:
    enabled: true
    retention: "30d"
    granularity: "1m"
  
  # Multi-region deployment
  multi_region:
    enabled: true
    primary_region: "us-east-1"
    secondary_region: "us-west-2" 
    failover_automatic: false  # Manual failover for medical devices
    rpo: "5m"  # Recovery Point Objective
    rto: "15m"  # Recovery Time Objective

# Performance requirements for medical device
performance:
  # SLA requirements
  sla:
    availability: "99.95%"  # Maximum 4.38 hours downtime per year
    response_time_p95: "2s"
    response_time_p99: "3s"
    error_rate: "<0.1%"
    
  # Medical device specific performance
  medical_performance:
    bom_generation_time: "<5s"  # FDA requirement
    page_load_time: "<3s"
    concurrent_users: "500+"
    data_processing_time: "<10s"
  
  # Load testing
  load_testing:
    enabled: true
    schedule: "monthly"
    scenarios:
      - name: "peak_usage"
        users: 500
        duration: "30m"
      - name: "stress_test"
        users: 1000
        duration: "15m"
    
  # Performance monitoring
  monitoring:
    synthetic_monitoring: true
    user_experience_monitoring: true
    infrastructure_monitoring: true
    
# Incident response for medical devices
incident_response:
  # Response team
  team:
    - role: "Incident Commander"
      contact: "@medical-device-lead"
    - role: "Technical Lead"
      contact: "@engineering-lead"
    - role: "Quality Assurance"
      contact: "@qa-lead"
    - role: "Regulatory Affairs"
      contact: "@regulatory-lead"
  
  # Escalation matrix
  escalation:
    p0_critical: "immediate"  # Patient safety impact
    p1_high: "15m"           # System unavailable
    p2_medium: "1h"          # Degraded performance
    p3_low: "24h"            # Minor issues
  
  # Communication plan
  communication:
    internal_notifications: ["slack", "email", "sms"]
    external_notifications: ["status_page", "customer_email"]
    regulatory_reporting: "as_required"
    
# Compliance reporting and documentation
compliance_reporting:
  automated_reports:
    - name: "Monthly Security Report"
      schedule: "0 0 1 * *"
      recipients: ["security-team", "compliance-team"]
    
    - name: "Quarterly Risk Assessment"
      schedule: "0 0 1 */3 *"  
      recipients: ["risk-committee", "regulatory-team"]
    
    - name: "Annual Compliance Audit"
      schedule: "0 0 1 1 *"
      recipients: ["executive-team", "board"]
  
  # Document management
  documentation:
    version_control: true
    change_tracking: true
    approval_workflow: true
    retention_policy: "regulatory_requirements"